version: '3'

services:
  bot:
    container_name: jmelody
    build:
      context: .
    tty: true
    volumes:
      - .\m2:/root/.m2
    links:
      - redis
    depends_on:
      - redis
    networks:
      - jmelody-network


  redis:
    container_name: jmelody-redis
    image: redis:alpine
    tty: true
    restart: always
    command: /bin/sh -c "redis-server --requirepass $$REDIS_HOST_PASSWORD"
    environment:
      - REDIS_HOST_PASSWORD=de8b7c40f7ad40119237612be96a758f
    ports:
      - "6379:6379"
    networks:
      - jmelody-network


networks:
  jmelody-network:
    driver: bridge